# Generated by Django 5.0.6 on 2024-06-08 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('cpf', models.CharField(max_length=14, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('driver_email', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Drivers',
            },
        ),
        migrations.CreateModel(
            name='ParkingSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spot_number', models.IntegerField(unique=True)),
                ('is_occupied', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'ParkingSpots',
            },
        ),
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=29)),
                ('street', models.CharField(max_length=20)),
                ('house_number', models.IntegerField()),
                ('cep', models.CharField(max_length=9)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='park_app.driver')),
            ],
            options={
                'verbose_name_plural': 'Adress',
            },
        ),
        migrations.CreateModel(
            name='EntryRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_entry', models.DateTimeField()),
                ('parking_spot_status', models.BooleanField(default=False)),
                ('driver_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='park_app.driver')),
            ],
            options={
                'verbose_name_plural': 'EntryRegisters',
            },
        ),
        migrations.CreateModel(
            name='ExitRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exit', models.DateTimeField()),
                ('payment', models.DecimalField(decimal_places=2, max_digits=6)),
                ('payment_method', models.CharField(max_length=20)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='park_app.entryregister')),
            ],
            options={
                'verbose_name_plural': 'ExitRegisters',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=8)),
                ('vehicle_model', models.CharField(max_length=20)),
                ('vehicle_cor', models.CharField(max_length=20)),
                ('vehicle_year', models.DateField()),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='park_app.driver')),
            ],
            options={
                'verbose_name_plural': 'Vehicles',
            },
        ),
        migrations.AddField(
            model_name='entryregister',
            name='vehicle_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='park_app.vehicle'),
        ),
    ]
